// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChOJ6m9UrqPnqIArBCQ1SopgOUrp0QfMQ',
    appId: '1:864465678113:web:e74a45a91e88a25b929860',
    messagingSenderId: '864465678113',
    projectId: 'sites-app-f6af0',
    authDomain: 'sites-app-f6af0.firebaseapp.com',
    storageBucket: 'sites-app-f6af0.firebasestorage.app',
    measurementId: 'G-KJF3MQK69S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1fp8kVQlMhiTlhSdHd4Yz46E5hNHww4w',
    appId: '1:864465678113:android:ef6765d1b2251995929860',
    messagingSenderId: '864465678113',
    projectId: 'sites-app-f6af0',
    storageBucket: 'sites-app-f6af0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9artUaYjSww3_4LmqllOieiy6L1pQQME',
    appId: '1:864465678113:ios:ed5033fce144c542929860',
    messagingSenderId: '864465678113',
    projectId: 'sites-app-f6af0',
    storageBucket: 'sites-app-f6af0.firebasestorage.app',
    iosBundleId: 'com.example.sitesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9artUaYjSww3_4LmqllOieiy6L1pQQME',
    appId: '1:864465678113:ios:ed5033fce144c542929860',
    messagingSenderId: '864465678113',
    projectId: 'sites-app-f6af0',
    storageBucket: 'sites-app-f6af0.firebasestorage.app',
    iosBundleId: 'com.example.sitesProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChOJ6m9UrqPnqIArBCQ1SopgOUrp0QfMQ',
    appId: '1:864465678113:web:ae05579946fbe628929860',
    messagingSenderId: '864465678113',
    projectId: 'sites-app-f6af0',
    authDomain: 'sites-app-f6af0.firebaseapp.com',
    storageBucket: 'sites-app-f6af0.firebasestorage.app',
    measurementId: 'G-XH1SSZT91N',
  );
}
